### ISSUE TITLE
你好，请问V2版本出来了吗？

### ISSUE THREAD

**Issue by JackLicc** [hillpy/MiniProgramSDK#1]
找了一圈，发现你写的最全，

请问V2版本出来了吗？

**Comment by shinn-lancelot** [comment]
目前还在测试当中哦，测试完成可以发测试版，然后再写v2文档哈，感谢您的issue～

**Comment by JackLicc** [comment]
> 目前还在测试当中哦，测试完成可以发测试版，然后再写v2文档哈，感谢您的issue～

我现在用这个sdk，不会有啥问题吧。

**Comment by shinn-lancelot** [comment]
v1版本没什么问题的
